dist: trusty
addons:
  ssh_known_hosts:
  - 185.65.137.105:2200
env:
  - secure: "y2ues1utJkn++o7i98nmr6TiHx+G2zHtURiSTP0h37Y9/BnTf421AAVY/D2FpHs1RTIzA5NVj5tCFLTZI5nJQFOhE7LXAssI6t1GZm6mP+8pPq5XvOM8HzdcvFA3pI+Wr8iXfIaa0Txw/XoMU+smkY6QJGy1r2Qa8qW2TXsUjACvbYZjumXJsJFQpFINFkACnbR8yntdwk6/RNfClvLII7A59rgWiGg6ucTKfPQnt9wZ5i4Itm7qQIk61RfErHgL4wjzFsWRBQlEmR0WTIbQYLanHP0Kz/Xpr0rQwdI1lURkIvgpYdWew211OteiPGm3DLwj1YSAqWkkEt19sR1hR+MzpFbxy82xe/UxF05706C5Zfh8hlCKo2w9pXNzR8dJXCNvI+/iqQM5axFdJ0STr8ZjPIEP3l5vTH6OLVSku6SU5LEJ1TT/ILKdlLrqORkfyzrpABZuPgaA2wsznPlhFi6TYOrSkXxhKu0nJ85IqTCiWOfZ45p2+3s0y36ioSett3+5XYpdBnWUDascGEI0raxeiA5jzAKTHTbP0xiBmq7GKeUdrjyUMbTZFC44dQOtR16BUsJcZ6YuymMBG+A+Z/lrpb2Zdlw1T3nWaN1Qv2CYaXiH4Vtvv+V5uhvsrHy/OTDxGej3DRc4/aONyavyuSw/apViPt73qVC/6rcXNbY="
  - secure: "ThFEw41PCiP++e8eyPKRxnDMt75R3OWXzc027WIfor2Sr11TAoSgqE4uAEOmVj7f+X/MtnLLTuZ+xmDaCCaUy1/vX4b+vElrhudP9gCYB1iczHigrYlwiRYgqGsA4Us6F1BWzwAq/JPslGHrWomJCeXB9TMxhIT7o6T0WnaGZdrCATkwgb1OxnSka+iXL3iH3LAalWU808Pr9ZEYPK30AORdThh4BgHwpGjZdmzta/lfHYjSL9QOvNoZ0FWEWXW/YogJBCmpReTbtkRbBXPgiCt7kNssph4lfALDp3W21AJHv/BSCNZSPjLIn8jARRf040LvXso7BKiAAP9zQMh3HWtBylqyVIpUwP2Ss1Dq/LFhW3vWsXSScNwDGCe3O/OGeuSONi5Z5RlQpVj4JVxs5GkkGNylWoPQ3ywMlLfbpWsUhxb0zKxhzPxQM2hQO7QwTjiNikZE8wlpJLoafiGMUTe1I51vC8i3ADl5CsJ/L2kegpfkCX2IkY459DeaUQ48SG8VzIro24Pxvh232bJM2WMgLOcEJOQ4pLftkQ4YRpg6HXVUUbBqdoF4C5ojxMx088aqK0ZwcunRIBNGeR9Dh6arsXd+n4i7UmDel5asCA5tSsO8k2nvt2Z9vMQ2tWqJaZ9lIYD6BSLHKCwXMbLH5ttxXZws3dClaf6tvxhNxJg="
  - secure: "e1xJWm4IirDdKz+F8CJTapiwTIhatuuweSpkjL8wnKPZZ2ALifOJCNX1nIbGU3VO8of0muyZ5yE0OOwI2islRJbnMlEeO0vB7TOPa1LYIrc2KOPaYW3vEr8pGpUAlR3Lz/KkzS6cX+vgnMi7GllceUtmfGtykuafCbqMiW+v8uVgEv2IYuhUuw6dMtfM2xVjtcuHHzN6OiaIvjNvHqwwv17dJrnpcYBhYwXJSi/q/t07gkBXY9AIMvf1ymVk/tM4lNUKRCOZJhDvcbVyEVpXwbghe5zdbw5ES0rJgEj/HDSuDJ5SyvHNuHMZkPthlASAIGiDEFLm3IXz3PO5uWCxYdokKTd3sQErpIqXzftyLpxWC0dbHWFgiUOe2xQPHgrIbR/3xfUCdZj3ZqnOEfOa/h/Ob8cmmAzpydWhEweKoNqf+TKe55yOa3Pn5bUgUAN7ctkmdsordIICPmdhqDo2qe7LFCRxVYHw0MSt5p0mAva4jRKoG8aL6cR+LMJ+N50TcRl/KltLlK0TQB/NcaKzgQGWdSx71FAdzHuaT9gLV7sbaUIbA5DVSGZnuwZ0Ox4ILGKjhkgF/qihtD5WCauU9Ne8qkjhgMFMOjTiglSNTnoCT1RFvXe8HSevdeO/1E+1I1x96hsyUqPoXFeiSkiPYj4w0vMwY2W/nRY+WjBX6O8="

language: node_js
node_js:
  - "8.1.4"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g npm@5.2.0
  - npm install
script: npm test
after_success:
  - find /home/travis/build/WebTownIP/centr-estetika.by -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} $FTP_HOST/{} \;

notifications:
  email:
    recipients:
      - nikita.sedyx.94@gmail.com
    on_success: always
