language: node_js
dist: trusty
node_js:
  - "8.1.4"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g npm@5.2.0
  - npm install
script: npm test
after_success:
  - ssh 185.65.137.105 -p 2200 -l root

notifications:
  email:
    recipients:
      - nikita.sedyx.94@gmail.com
    on_success: always
