dist: trusty
addons:
  ssh_known_hosts:
  - 185.65.137.105:2200
env:
  global:
    - secure: "y2ues1utJkn++o7i98nmr6TiHx+G2zHtURiSTP0h37Y9/BnTf421AAVY/D2FpHs1RTIzA5NVj5tCFLTZI5nJQFOhE7LXAssI6t1GZm6mP+8pPq5XvOM8HzdcvFA3pI+Wr8iXfIaa0Txw/XoMU+smkY6QJGy1r2Qa8qW2TXsUjACvbYZjumXJsJFQpFINFkACnbR8yntdwk6/RNfClvLII7A59rgWiGg6ucTKfPQnt9wZ5i4Itm7qQIk61RfErHgL4wjzFsWRBQlEmR0WTIbQYLanHP0Kz/Xpr0rQwdI1lURkIvgpYdWew211OteiPGm3DLwj1YSAqWkkEt19sR1hR+MzpFbxy82xe/UxF05706C5Zfh8hlCKo2w9pXNzR8dJXCNvI+/iqQM5axFdJ0STr8ZjPIEP3l5vTH6OLVSku6SU5LEJ1TT/ILKdlLrqORkfyzrpABZuPgaA2wsznPlhFi6TYOrSkXxhKu0nJ85IqTCiWOfZ45p2+3s0y36ioSett3+5XYpdBnWUDascGEI0raxeiA5jzAKTHTbP0xiBmq7GKeUdrjyUMbTZFC44dQOtR16BUsJcZ6YuymMBG+A+Z/lrpb2Zdlw1T3nWaN1Qv2CYaXiH4Vtvv+V5uhvsrHy/OTDxGej3DRc4/aONyavyuSw/apViPt73qVC/6rcXNbY="
    - secure: "ThFEw41PCiP++e8eyPKRxnDMt75R3OWXzc027WIfor2Sr11TAoSgqE4uAEOmVj7f+X/MtnLLTuZ+xmDaCCaUy1/vX4b+vElrhudP9gCYB1iczHigrYlwiRYgqGsA4Us6F1BWzwAq/JPslGHrWomJCeXB9TMxhIT7o6T0WnaGZdrCATkwgb1OxnSka+iXL3iH3LAalWU808Pr9ZEYPK30AORdThh4BgHwpGjZdmzta/lfHYjSL9QOvNoZ0FWEWXW/YogJBCmpReTbtkRbBXPgiCt7kNssph4lfALDp3W21AJHv/BSCNZSPjLIn8jARRf040LvXso7BKiAAP9zQMh3HWtBylqyVIpUwP2Ss1Dq/LFhW3vWsXSScNwDGCe3O/OGeuSONi5Z5RlQpVj4JVxs5GkkGNylWoPQ3ywMlLfbpWsUhxb0zKxhzPxQM2hQO7QwTjiNikZE8wlpJLoafiGMUTe1I51vC8i3ADl5CsJ/L2kegpfkCX2IkY459DeaUQ48SG8VzIro24Pxvh232bJM2WMgLOcEJOQ4pLftkQ4YRpg6HXVUUbBqdoF4C5ojxMx088aqK0ZwcunRIBNGeR9Dh6arsXd+n4i7UmDel5asCA5tSsO8k2nvt2Z9vMQ2tWqJaZ9lIYD6BSLHKCwXMbLH5ttxXZws3dClaf6tvxhNxJg="
    - secure: "w+PYTn/kxpgh8xWV6LAKb2cF9I5bnr9ZU9I/q+xFTTwDeQ4g1+dbTI4JRJ1ADRw+0zN3LgTw3c0I/bLR3L8bIdOqoh0xR0mLz22HwOeBtE+genfh86QWAKF0/1CcRaSEgOWzRur9rDZYr1ghCYlAi+p3RyC7bVJpK550DTgRS26LLRuDUdm6JzLumqfUCs4zolHCyaUl1dWQgod//zt440dVQwr1bJMGcRVtGTp72dFxTIb/8moc6ZQV8tGoSqA/+10QYfgS62AEBEbQcMgPESC3IGtmjvCOfRnUzY84gNTKDiHi3W0R/v5/sEfR6h5aiUnVOIwNk7j6s0aPf+vgcO5bukcAzrsKF+xjd/rIu6l3eZg8Ee77WnL50RazmJ8iM7qNIWKma3VSHrITFgWbNOm1bjvOFTJDT2i5hwUkw1oS5jWU2RCbnJpzMqrjHUOdX5QEElzjPFvIxSKolw3FSxtBtS0juYxihuqWgyNBmPCT+60IPNFBVDj+JRHkwFWN9F1VEcuy8z2cK5M9Wd1YLG7Ck6HAZ3QXjVEuCcDYNc2KBRsMFXDPeVo22tljz3LrxgBKhiHkMCE2mpfO/CO6OhSkUyJUkFRC+83h+IiRUc0x6uNb9+Rqn13Jocz8QgbWz0txxG8GvCtApg9RRh3GZyWb+3WKIcgno2U6CJ3E4m0="

language: node_js
node_js:
  - "8.1.4"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g npm@5.2.0
  - npm install
script:
  - npm test
  - npm run deploy
after_success:
  - echo $FTP_HOST
  - find /home/travis/build/WebTownIP/centr-estetika.by/dist -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} $FTP_HOST\{} \;

notifications:
  email:
    recipients:
      - nikita.sedyx.94@gmail.com
    on_success: always
