dist: trusty
addons:
  ssh_known_hosts:
  - 185.65.137.105:2200

language: node_js
node_js:
  - "8.1.4"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g npm@5.2.0
  - npm install
script: npm test
after_success:
  - cd /home/travis/build/WebTownIP/centr-estetika.by
  - ls
  - zip dist.zip /home/travis/build/WebTownIP/centr-estetika.by
  - ls

notifications:
  email:
    recipients:
      - nikita.sedyx.94@gmail.com
    on_success: always
